import 'package:innovareti_test/models/room_model.dart';

class MockedRoomModel {
  List<String> listOfFeaturesToCheck = [
    'Wi-Fi',
    'TV',
    'Projetor',
    'Quadro Interativo',
    'Tablet',
    'Computador',
  ];

  final listOfModels = [
    RoomModel(
      id: 1,
      name: 'Sala 1',
      imageUrl: 'assets/images/room_one.jpg',
      capacity: 8,
      address: 'Av. Bom Senhor, 3454 - São Paulo.',
      hasBigScreenTv: true,
      hasInteractiveBoard: true,
      hasPersonalComputer: false,
      hasPersonalTablet: true,
      hasProjector: false,
      hasWifi: true,
    ),
    RoomModel(
      id: 2,
      name: 'Sala 2',
      imageUrl: 'assets/images/room_two.jpg',
      capacity: 5,
      address: 'Av. Nossa Senhora da Bondade, 1203 - São Paulo.',
      hasBigScreenTv: true,
      hasInteractiveBoard: false,
      hasPersonalComputer: false,
      hasPersonalTablet: false,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 3,
      name: 'Sala 3',
      imageUrl: 'assets/images/room_three.jpg',
      capacity: 7,
      address: 'Av. Todos os Santos, 4333 - São Paulo.',
      hasBigScreenTv: true,
      hasInteractiveBoard: false,
      hasPersonalComputer: false,
      hasPersonalTablet: true,
      hasProjector: false,
      hasWifi: true,
    ),
    RoomModel(
      id: 4,
      name: 'Sala 4',
      imageUrl: 'assets/images/room_four.jpg',
      capacity: 12,
      address: 'Av. Ricardo Carvalho, 4557 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: true,
      hasPersonalComputer: true,
      hasPersonalTablet: false,
      hasProjector: false,
      hasWifi: true,
    ),
    RoomModel(
      id: 5,
      name: 'Sala 5',
      imageUrl: 'assets/images/room_five.jpg',
      capacity: 16,
      address: 'Av. São Pedro de Alcântara, 2324 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: false,
      hasPersonalComputer: false,
      hasPersonalTablet: true,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 6,
      name: 'Sala 6',
      imageUrl: 'assets/images/room_six.jpg',
      capacity: 6,
      address: 'Av. Nossos Senhores, 454 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: false,
      hasPersonalComputer: false,
      hasPersonalTablet: true,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 7,
      name: 'Sala 7',
      imageUrl: 'assets/images/room_seven.jpg',
      capacity: 10,
      address: 'Av. Dionísio Ferreira, 989 - São Paulo.',
      hasBigScreenTv: true,
      hasInteractiveBoard: false,
      hasPersonalComputer: true,
      hasPersonalTablet: false,
      hasProjector: false,
      hasWifi: true,
    ),
    RoomModel(
      id: 8,
      name: 'Sala 8',
      imageUrl: 'assets/images/room_eight.jpg',
      capacity: 12,
      address: 'Av. Hernandes Maciel, 6543 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: true,
      hasPersonalComputer: false,
      hasPersonalTablet: false,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 9,
      name: 'Sala 9',
      imageUrl: 'assets/images/room_nine.jpg',
      capacity: 14,
      address: 'Av. Hernesto Piauí, 3455 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: true,
      hasPersonalComputer: false,
      hasPersonalTablet: false,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 10,
      name: 'Sala 10',
      imageUrl: 'assets/images/room_ten.jpg',
      capacity: 8,
      address: 'Av. Tremondes dos Santos, 1233 - São Paulo.',
      hasBigScreenTv: true,
      hasInteractiveBoard: false,
      hasPersonalComputer: true,
      hasPersonalTablet: false,
      hasProjector: true,
      hasWifi: true,
    ),
    RoomModel(
      id: 11,
      name: 'Sala 11',
      imageUrl: 'assets/images/room_eleven.jpg',
      capacity: 3,
      address: 'Av. Casa dos Nomes, 6775 - São Paulo.',
      hasBigScreenTv: false,
      hasInteractiveBoard: false,
      hasPersonalComputer: false,
      hasPersonalTablet: false,
      hasProjector: false,
      hasWifi: false,
    ),
  ];
}
